// Code generated by MockGen. DO NOT EDIT.
// Source: ../v1/v1connect/task.connect.go
//
// Generated by this command:
//
//	mockgen -source=../v1/v1connect/task.connect.go -destination=./mocks/task.connect_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/furisto/construct/api/go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskServiceClient is a mock of TaskServiceClient interface.
type MockTaskServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceClientMockRecorder
	isgomock struct{}
}

// MockTaskServiceClientMockRecorder is the mock recorder for MockTaskServiceClient.
type MockTaskServiceClientMockRecorder struct {
	mock *MockTaskServiceClient
}

// NewMockTaskServiceClient creates a new mock instance.
func NewMockTaskServiceClient(ctrl *gomock.Controller) *MockTaskServiceClient {
	mock := &MockTaskServiceClient{ctrl: ctrl}
	mock.recorder = &MockTaskServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskServiceClient) EXPECT() *MockTaskServiceClientMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskServiceClient) CreateTask(arg0 context.Context, arg1 *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskServiceClientMockRecorder) CreateTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskServiceClient)(nil).CreateTask), arg0, arg1)
}

// DeleteTask mocks base method.
func (m *MockTaskServiceClient) DeleteTask(arg0 context.Context, arg1 *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskServiceClientMockRecorder) DeleteTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskServiceClient)(nil).DeleteTask), arg0, arg1)
}

// GetTask mocks base method.
func (m *MockTaskServiceClient) GetTask(arg0 context.Context, arg1 *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTaskServiceClientMockRecorder) GetTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskServiceClient)(nil).GetTask), arg0, arg1)
}

// ListTasks mocks base method.
func (m *MockTaskServiceClient) ListTasks(arg0 context.Context, arg1 *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListTasksResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockTaskServiceClientMockRecorder) ListTasks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockTaskServiceClient)(nil).ListTasks), arg0, arg1)
}

// Subscribe mocks base method.
func (m *MockTaskServiceClient) Subscribe(arg0 context.Context, arg1 *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.SubscribeResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(*connect.ServerStreamForClient[v1.SubscribeResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockTaskServiceClientMockRecorder) Subscribe(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockTaskServiceClient)(nil).Subscribe), arg0, arg1)
}

// SuspendTask mocks base method.
func (m *MockTaskServiceClient) SuspendTask(arg0 context.Context, arg1 *connect.Request[v1.SuspendTaskRequest]) (*connect.Response[v1.SuspendTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuspendTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.SuspendTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuspendTask indicates an expected call of SuspendTask.
func (mr *MockTaskServiceClientMockRecorder) SuspendTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendTask", reflect.TypeOf((*MockTaskServiceClient)(nil).SuspendTask), arg0, arg1)
}

// UpdateTask mocks base method.
func (m *MockTaskServiceClient) UpdateTask(arg0 context.Context, arg1 *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskServiceClientMockRecorder) UpdateTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskServiceClient)(nil).UpdateTask), arg0, arg1)
}

// MockTaskServiceHandler is a mock of TaskServiceHandler interface.
type MockTaskServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceHandlerMockRecorder
	isgomock struct{}
}

// MockTaskServiceHandlerMockRecorder is the mock recorder for MockTaskServiceHandler.
type MockTaskServiceHandlerMockRecorder struct {
	mock *MockTaskServiceHandler
}

// NewMockTaskServiceHandler creates a new mock instance.
func NewMockTaskServiceHandler(ctrl *gomock.Controller) *MockTaskServiceHandler {
	mock := &MockTaskServiceHandler{ctrl: ctrl}
	mock.recorder = &MockTaskServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskServiceHandler) EXPECT() *MockTaskServiceHandlerMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskServiceHandler) CreateTask(arg0 context.Context, arg1 *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskServiceHandlerMockRecorder) CreateTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskServiceHandler)(nil).CreateTask), arg0, arg1)
}

// DeleteTask mocks base method.
func (m *MockTaskServiceHandler) DeleteTask(arg0 context.Context, arg1 *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskServiceHandlerMockRecorder) DeleteTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskServiceHandler)(nil).DeleteTask), arg0, arg1)
}

// GetTask mocks base method.
func (m *MockTaskServiceHandler) GetTask(arg0 context.Context, arg1 *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTaskServiceHandlerMockRecorder) GetTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskServiceHandler)(nil).GetTask), arg0, arg1)
}

// ListTasks mocks base method.
func (m *MockTaskServiceHandler) ListTasks(arg0 context.Context, arg1 *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListTasksResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockTaskServiceHandlerMockRecorder) ListTasks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockTaskServiceHandler)(nil).ListTasks), arg0, arg1)
}

// Subscribe mocks base method.
func (m *MockTaskServiceHandler) Subscribe(arg0 context.Context, arg1 *connect.Request[v1.SubscribeRequest], arg2 *connect.ServerStream[v1.SubscribeResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockTaskServiceHandlerMockRecorder) Subscribe(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockTaskServiceHandler)(nil).Subscribe), arg0, arg1, arg2)
}

// SuspendTask mocks base method.
func (m *MockTaskServiceHandler) SuspendTask(arg0 context.Context, arg1 *connect.Request[v1.SuspendTaskRequest]) (*connect.Response[v1.SuspendTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuspendTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.SuspendTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuspendTask indicates an expected call of SuspendTask.
func (mr *MockTaskServiceHandlerMockRecorder) SuspendTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendTask", reflect.TypeOf((*MockTaskServiceHandler)(nil).SuspendTask), arg0, arg1)
}

// UpdateTask mocks base method.
func (m *MockTaskServiceHandler) UpdateTask(arg0 context.Context, arg1 *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateTaskResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskServiceHandlerMockRecorder) UpdateTask(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskServiceHandler)(nil).UpdateTask), arg0, arg1)
}
