// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/furisto/construct/frontend/cli/cmd (interfaces: UserInfo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/user_info_mock.go -package=mocks . UserInfo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserInfo is a mock of UserInfo interface.
type MockUserInfo struct {
	ctrl     *gomock.Controller
	recorder *MockUserInfoMockRecorder
	isgomock struct{}
}

// MockUserInfoMockRecorder is the mock recorder for MockUserInfo.
type MockUserInfoMockRecorder struct {
	mock *MockUserInfo
}

// NewMockUserInfo creates a new mock instance.
func NewMockUserInfo(ctrl *gomock.Controller) *MockUserInfo {
	mock := &MockUserInfo{ctrl: ctrl}
	mock.recorder = &MockUserInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInfo) EXPECT() *MockUserInfoMockRecorder {
	return m.recorder
}

// ConstructDir mocks base method.
func (m *MockUserInfo) ConstructDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConstructDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConstructDir indicates an expected call of ConstructDir.
func (mr *MockUserInfoMockRecorder) ConstructDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConstructDir", reflect.TypeOf((*MockUserInfo)(nil).ConstructDir))
}

// HomeDir mocks base method.
func (m *MockUserInfo) HomeDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HomeDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HomeDir indicates an expected call of HomeDir.
func (mr *MockUserInfoMockRecorder) HomeDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HomeDir", reflect.TypeOf((*MockUserInfo)(nil).HomeDir))
}

// UserID mocks base method.
func (m *MockUserInfo) UserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockUserInfoMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockUserInfo)(nil).UserID))
}
