// Agent API provides CRUD operations for managing AI agents within Construct.
// Agents are autonomous AI entities that can perform tasks, execute code, and interact
// with users based on their configured instructions and model capabilities.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: construct/v1/agent.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent represents a complete agent entity with metadata, specification, and status.
type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata contains immutable and system-managed fields about the agent.
	Metadata *AgentMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Spec contains the desired state of the agent, configured by the user.
	Spec          *AgentSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_construct_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Agent) GetSpec() *AgentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// AgentMetadata contains system-managed, immutable information about an agent.
type AgentMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier for the agent (UUID format).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// created_at is the timestamp when the agent was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the timestamp when the agent was last modified.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetadata) Reset() {
	*x = AgentMetadata{}
	mi := &file_construct_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetadata) ProtoMessage() {}

func (x *AgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetadata.ProtoReflect.Descriptor instead.
func (*AgentMetadata) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AgentSpec defines the user-configurable specification of an agent.
type AgentSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the human-readable name of the agent (1-255 characters).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description provides a brief summary of the agent's purpose (max 2048 characters).
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// instructions define the agent's behavior and capabilities (1-10000 characters).
	Instructions string `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	// model_id references the AI model that powers this agent (UUID format).
	ModelId       string `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSpec) Reset() {
	*x = AgentSpec{}
	mi := &file_construct_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSpec) ProtoMessage() {}

func (x *AgentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSpec.ProtoReflect.Descriptor instead.
func (*AgentSpec) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentSpec) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *AgentSpec) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// CreateAgentRequest contains the parameters needed to create a new agent.
type CreateAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the human-readable name for the new agent (1-255 characters).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description provides a brief summary of the agent's purpose (max 2048 characters).
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// instructions define the agent's behavior and capabilities (1-65536 characters).
	Instructions string `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	// model_id references the AI model that will power this agent (UUID format).
	ModelId       string `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_construct_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAgentRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *CreateAgentRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// CreateAgentResponse contains the newly created agent.
type CreateAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent is the newly created agent instance.
	Agent         *Agent `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	mi := &file_construct_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// GetAgentRequest specifies which agent to retrieve.
type GetAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the agent to retrieve (UUID format).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_construct_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetAgentResponse contains the requested agent.
type GetAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent is the requested agent instance.
	Agent         *Agent `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_construct_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// ListAgentsRequest specifies parameters for listing agents with optional filtering and pagination.
type ListAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// filter specifies criteria for narrowing the results.
	Filter *ListAgentsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// page_size limits the number of agents returned per page (1-100).
	PageSize *int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// page_token is used for pagination to retrieve subsequent pages.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// sort_field specifies which field to sort results by.
	SortField *SortField `protobuf:"varint,4,opt,name=sort_field,json=sortField,proto3,enum=construct.v1.SortField,oneof" json:"sort_field,omitempty"`
	// sort_order specifies the sorting direction (ascending or descending).
	SortOrder     *SortOrder `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=construct.v1.SortOrder,oneof" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_construct_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsRequest) GetFilter() *ListAgentsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAgentsRequest) GetSortField() SortField {
	if x != nil && x.SortField != nil {
		return *x.SortField
	}
	return SortField_SORT_FIELD_UNSPECIFIED
}

func (x *ListAgentsRequest) GetSortOrder() SortOrder {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

// ListAgentsResponse contains the list of agents matching the request criteria.
type ListAgentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agents is the list of agents matching the filter criteria.
	Agents []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	// next_page_token is used to retrieve the next page of results (empty if no more pages).
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_construct_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpdateAgentRequest specifies which agent to update and the new values for its fields.
type UpdateAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the agent to update (UUID format).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the new name for the agent (1-255 characters, optional).
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// description is the new description for the agent (max 1000 characters, optional).
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// instructions are the new instructions for the agent (1-10000 characters, optional).
	Instructions *string `protobuf:"bytes,4,opt,name=instructions,proto3,oneof" json:"instructions,omitempty"`
	// model_id is the new model reference for the agent (UUID format, optional).
	ModelId       *string `protobuf:"bytes,5,opt,name=model_id,json=modelId,proto3,oneof" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_construct_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAgentRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAgentRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateAgentRequest) GetInstructions() string {
	if x != nil && x.Instructions != nil {
		return *x.Instructions
	}
	return ""
}

func (x *UpdateAgentRequest) GetModelId() string {
	if x != nil && x.ModelId != nil {
		return *x.ModelId
	}
	return ""
}

// UpdateAgentResponse contains the updated agent.
type UpdateAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent is the updated agent instance.
	Agent         *Agent `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentResponse) Reset() {
	*x = UpdateAgentResponse{}
	mi := &file_construct_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentResponse) ProtoMessage() {}

func (x *UpdateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// DeleteAgentRequest specifies which agent to delete.
type DeleteAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the agent to delete (UUID format).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_construct_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteAgentResponse confirms the agent deletion (empty response).
type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_construct_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{12}
}

// Filter specifies criteria for narrowing the list of returned agents.
type ListAgentsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// names filters agents by their names (max 64 unique names, each 1-255 characters).
	Names         []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest_Filter) Reset() {
	*x = ListAgentsRequest_Filter{}
	mi := &file_construct_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest_Filter) ProtoMessage() {}

func (x *ListAgentsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_construct_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_construct_v1_agent_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListAgentsRequest_Filter) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_construct_v1_agent_proto protoreflect.FileDescriptor

const file_construct_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18construct/v1/agent.proto\x12\fconstruct.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19construct/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"m\n" +
	"\x05Agent\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.construct.v1.AgentMetadataR\bmetadata\x12+\n" +
	"\x04spec\x18\x02 \x01(\v2\x17.construct.v1.AgentSpecR\x04spec\"\xaf\x01\n" +
	"\rAgentMetadata\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12A\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x12A\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tupdatedAt\"\xad\x01\n" +
	"\tAgentSpec\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\vdescription\x12/\n" +
	"\finstructions\x18\x03 \x01(\tB\v\xbaH\br\x06\x10\x01\x18\x80\x80\x04R\finstructions\x12#\n" +
	"\bmodel_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\amodelId\"\xb6\x01\n" +
	"\x12CreateAgentRequest\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\vdescription\x12/\n" +
	"\finstructions\x18\x03 \x01(\tB\v\xbaH\br\x06\x10\x01\x18\x80\x80\x04R\finstructions\x12#\n" +
	"\bmodel_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\amodelId\"H\n" +
	"\x13CreateAgentResponse\x121\n" +
	"\x05agent\x18\x01 \x01(\v2\x13.construct.v1.AgentB\x06\xbaH\x03\xc8\x01\x01R\x05agent\"+\n" +
	"\x0fGetAgentRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"E\n" +
	"\x10GetAgentResponse\x121\n" +
	"\x05agent\x18\x01 \x01(\v2\x13.construct.v1.AgentB\x06\xbaH\x03\xc8\x01\x01R\x05agent\"\x98\x03\n" +
	"\x11ListAgentsRequest\x12>\n" +
	"\x06filter\x18\x01 \x01(\v2&.construct.v1.ListAgentsRequest.FilterR\x06filter\x12+\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01H\x00R\bpageSize\x88\x01\x01\x12'\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\tpageToken\x12E\n" +
	"\n" +
	"sort_field\x18\x04 \x01(\x0e2\x17.construct.v1.SortFieldB\b\xbaH\x05\x82\x01\x02\x10\x01H\x01R\tsortField\x88\x01\x01\x12E\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2\x17.construct.v1.SortOrderB\b\xbaH\x05\x82\x01\x02\x10\x01H\x02R\tsortOrder\x88\x01\x01\x1a3\n" +
	"\x06Filter\x12)\n" +
	"\x05names\x18\x01 \x03(\tB\x13\xbaH\x10\x92\x01\r\x10@\x18\x01\"\ar\x05\x10\x01\x18\xff\x01R\x05namesB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_sort_fieldB\r\n" +
	"\v_sort_order\"i\n" +
	"\x12ListAgentsResponse\x12+\n" +
	"\x06agents\x18\x01 \x03(\v2\x13.construct.v1.AgentR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9a\x02\n" +
	"\x12UpdateAgentRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12#\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01H\x00R\x04name\x88\x01\x01\x12/\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aH\x01R\vdescription\x88\x01\x01\x123\n" +
	"\finstructions\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x90NH\x02R\finstructions\x88\x01\x01\x12(\n" +
	"\bmodel_id\x18\x05 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x03R\amodelId\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_instructionsB\v\n" +
	"\t_model_id\"H\n" +
	"\x13UpdateAgentResponse\x121\n" +
	"\x05agent\x18\x01 \x01(\v2\x13.construct.v1.AgentB\x06\xbaH\x03\xc8\x01\x01R\x05agent\".\n" +
	"\x12DeleteAgentRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x15\n" +
	"\x13DeleteAgentResponse2\xb6\x03\n" +
	"\fAgentService\x12T\n" +
	"\vCreateAgent\x12 .construct.v1.CreateAgentRequest\x1a!.construct.v1.CreateAgentResponse\"\x00\x12N\n" +
	"\bGetAgent\x12\x1d.construct.v1.GetAgentRequest\x1a\x1e.construct.v1.GetAgentResponse\"\x03\x90\x02\x01\x12T\n" +
	"\n" +
	"ListAgents\x12\x1f.construct.v1.ListAgentsRequest\x1a .construct.v1.ListAgentsResponse\"\x03\x90\x02\x01\x12T\n" +
	"\vUpdateAgent\x12 .construct.v1.UpdateAgentRequest\x1a!.construct.v1.UpdateAgentResponse\"\x00\x12T\n" +
	"\vDeleteAgent\x12 .construct.v1.DeleteAgentRequest\x1a!.construct.v1.DeleteAgentResponse\"\x00B(Z&github.com/furisto/construct/api/go/v1b\x06proto3"

var (
	file_construct_v1_agent_proto_rawDescOnce sync.Once
	file_construct_v1_agent_proto_rawDescData []byte
)

func file_construct_v1_agent_proto_rawDescGZIP() []byte {
	file_construct_v1_agent_proto_rawDescOnce.Do(func() {
		file_construct_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_construct_v1_agent_proto_rawDesc), len(file_construct_v1_agent_proto_rawDesc)))
	})
	return file_construct_v1_agent_proto_rawDescData
}

var file_construct_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_construct_v1_agent_proto_goTypes = []any{
	(*Agent)(nil),                    // 0: construct.v1.Agent
	(*AgentMetadata)(nil),            // 1: construct.v1.AgentMetadata
	(*AgentSpec)(nil),                // 2: construct.v1.AgentSpec
	(*CreateAgentRequest)(nil),       // 3: construct.v1.CreateAgentRequest
	(*CreateAgentResponse)(nil),      // 4: construct.v1.CreateAgentResponse
	(*GetAgentRequest)(nil),          // 5: construct.v1.GetAgentRequest
	(*GetAgentResponse)(nil),         // 6: construct.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),        // 7: construct.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),       // 8: construct.v1.ListAgentsResponse
	(*UpdateAgentRequest)(nil),       // 9: construct.v1.UpdateAgentRequest
	(*UpdateAgentResponse)(nil),      // 10: construct.v1.UpdateAgentResponse
	(*DeleteAgentRequest)(nil),       // 11: construct.v1.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),      // 12: construct.v1.DeleteAgentResponse
	(*ListAgentsRequest_Filter)(nil), // 13: construct.v1.ListAgentsRequest.Filter
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(SortField)(0),                   // 15: construct.v1.SortField
	(SortOrder)(0),                   // 16: construct.v1.SortOrder
}
var file_construct_v1_agent_proto_depIdxs = []int32{
	1,  // 0: construct.v1.Agent.metadata:type_name -> construct.v1.AgentMetadata
	2,  // 1: construct.v1.Agent.spec:type_name -> construct.v1.AgentSpec
	14, // 2: construct.v1.AgentMetadata.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: construct.v1.AgentMetadata.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: construct.v1.CreateAgentResponse.agent:type_name -> construct.v1.Agent
	0,  // 5: construct.v1.GetAgentResponse.agent:type_name -> construct.v1.Agent
	13, // 6: construct.v1.ListAgentsRequest.filter:type_name -> construct.v1.ListAgentsRequest.Filter
	15, // 7: construct.v1.ListAgentsRequest.sort_field:type_name -> construct.v1.SortField
	16, // 8: construct.v1.ListAgentsRequest.sort_order:type_name -> construct.v1.SortOrder
	0,  // 9: construct.v1.ListAgentsResponse.agents:type_name -> construct.v1.Agent
	0,  // 10: construct.v1.UpdateAgentResponse.agent:type_name -> construct.v1.Agent
	3,  // 11: construct.v1.AgentService.CreateAgent:input_type -> construct.v1.CreateAgentRequest
	5,  // 12: construct.v1.AgentService.GetAgent:input_type -> construct.v1.GetAgentRequest
	7,  // 13: construct.v1.AgentService.ListAgents:input_type -> construct.v1.ListAgentsRequest
	9,  // 14: construct.v1.AgentService.UpdateAgent:input_type -> construct.v1.UpdateAgentRequest
	11, // 15: construct.v1.AgentService.DeleteAgent:input_type -> construct.v1.DeleteAgentRequest
	4,  // 16: construct.v1.AgentService.CreateAgent:output_type -> construct.v1.CreateAgentResponse
	6,  // 17: construct.v1.AgentService.GetAgent:output_type -> construct.v1.GetAgentResponse
	8,  // 18: construct.v1.AgentService.ListAgents:output_type -> construct.v1.ListAgentsResponse
	10, // 19: construct.v1.AgentService.UpdateAgent:output_type -> construct.v1.UpdateAgentResponse
	12, // 20: construct.v1.AgentService.DeleteAgent:output_type -> construct.v1.DeleteAgentResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_construct_v1_agent_proto_init() }
func file_construct_v1_agent_proto_init() {
	if File_construct_v1_agent_proto != nil {
		return
	}
	file_construct_v1_common_proto_init()
	file_construct_v1_agent_proto_msgTypes[7].OneofWrappers = []any{}
	file_construct_v1_agent_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_construct_v1_agent_proto_rawDesc), len(file_construct_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_construct_v1_agent_proto_goTypes,
		DependencyIndexes: file_construct_v1_agent_proto_depIdxs,
		MessageInfos:      file_construct_v1_agent_proto_msgTypes,
	}.Build()
	File_construct_v1_agent_proto = out.File
	file_construct_v1_agent_proto_goTypes = nil
	file_construct_v1_agent_proto_depIdxs = nil
}
