// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/agent"
	"github.com/furisto/construct/backend/memory/model"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/google/uuid"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (au *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AgentUpdate) SetName(s string) *AgentUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AgentUpdate) SetNillableName(s *string) *AgentUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetDescription sets the "description" field.
func (au *AgentUpdate) SetDescription(s string) *AgentUpdate {
	au.mutation.SetDescription(s)
	return au
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (au *AgentUpdate) SetNillableDescription(s *string) *AgentUpdate {
	if s != nil {
		au.SetDescription(*s)
	}
	return au
}

// ClearDescription clears the value of the "description" field.
func (au *AgentUpdate) ClearDescription() *AgentUpdate {
	au.mutation.ClearDescription()
	return au
}

// SetInstructions sets the "instructions" field.
func (au *AgentUpdate) SetInstructions(s string) *AgentUpdate {
	au.mutation.SetInstructions(s)
	return au
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (au *AgentUpdate) SetNillableInstructions(s *string) *AgentUpdate {
	if s != nil {
		au.SetInstructions(*s)
	}
	return au
}

// SetModelID sets the "model" edge to the Model entity by ID.
func (au *AgentUpdate) SetModelID(id uuid.UUID) *AgentUpdate {
	au.mutation.SetModelID(id)
	return au
}

// SetNillableModelID sets the "model" edge to the Model entity by ID if the given value is not nil.
func (au *AgentUpdate) SetNillableModelID(id *uuid.UUID) *AgentUpdate {
	if id != nil {
		au = au.SetModelID(*id)
	}
	return au
}

// SetModel sets the "model" edge to the Model entity.
func (au *AgentUpdate) SetModel(m *Model) *AgentUpdate {
	return au.SetModelID(m.ID)
}

// AddDelegateIDs adds the "delegates" edge to the Agent entity by IDs.
func (au *AgentUpdate) AddDelegateIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddDelegateIDs(ids...)
	return au
}

// AddDelegates adds the "delegates" edges to the Agent entity.
func (au *AgentUpdate) AddDelegates(a ...*Agent) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.AddDelegateIDs(ids...)
}

// AddDelegatorIDs adds the "delegators" edge to the Agent entity by IDs.
func (au *AgentUpdate) AddDelegatorIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddDelegatorIDs(ids...)
	return au
}

// AddDelegators adds the "delegators" edges to the Agent entity.
func (au *AgentUpdate) AddDelegators(a ...*Agent) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.AddDelegatorIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (au *AgentUpdate) Mutation() *AgentMutation {
	return au.mutation
}

// ClearModel clears the "model" edge to the Model entity.
func (au *AgentUpdate) ClearModel() *AgentUpdate {
	au.mutation.ClearModel()
	return au
}

// ClearDelegates clears all "delegates" edges to the Agent entity.
func (au *AgentUpdate) ClearDelegates() *AgentUpdate {
	au.mutation.ClearDelegates()
	return au
}

// RemoveDelegateIDs removes the "delegates" edge to Agent entities by IDs.
func (au *AgentUpdate) RemoveDelegateIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveDelegateIDs(ids...)
	return au
}

// RemoveDelegates removes "delegates" edges to Agent entities.
func (au *AgentUpdate) RemoveDelegates(a ...*Agent) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.RemoveDelegateIDs(ids...)
}

// ClearDelegators clears all "delegators" edges to the Agent entity.
func (au *AgentUpdate) ClearDelegators() *AgentUpdate {
	au.mutation.ClearDelegators()
	return au
}

// RemoveDelegatorIDs removes the "delegators" edge to Agent entities by IDs.
func (au *AgentUpdate) RemoveDelegatorIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveDelegatorIDs(ids...)
	return au
}

// RemoveDelegators removes "delegators" edges to Agent entities.
func (au *AgentUpdate) RemoveDelegators(a ...*Agent) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.RemoveDelegatorIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AgentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AgentUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AgentUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AgentUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`memory: validator failed for field "Agent.name": %w`, err)}
		}
	}
	return nil
}

func (au *AgentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.Description(); ok {
		_spec.SetField(agent.FieldDescription, field.TypeString, value)
	}
	if au.mutation.DescriptionCleared() {
		_spec.ClearField(agent.FieldDescription, field.TypeString)
	}
	if value, ok := au.mutation.Instructions(); ok {
		_spec.SetField(agent.FieldInstructions, field.TypeString, value)
	}
	if au.mutation.ModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.ModelTable,
			Columns: []string{agent.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.ModelTable,
			Columns: []string{agent.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.DelegatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agent.DelegatesTable,
			Columns: agent.DelegatesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedDelegatesIDs(); len(nodes) > 0 && !au.mutation.DelegatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agent.DelegatesTable,
			Columns: agent.DelegatesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.DelegatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agent.DelegatesTable,
			Columns: agent.DelegatesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.DelegatorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   agent.DelegatorsTable,
			Columns: agent.DelegatorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedDelegatorsIDs(); len(nodes) > 0 && !au.mutation.DelegatorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   agent.DelegatorsTable,
			Columns: agent.DelegatorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.DelegatorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   agent.DelegatorsTable,
			Columns: agent.DelegatorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetName sets the "name" field.
func (auo *AgentUpdateOne) SetName(s string) *AgentUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableName(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetDescription sets the "description" field.
func (auo *AgentUpdateOne) SetDescription(s string) *AgentUpdateOne {
	auo.mutation.SetDescription(s)
	return auo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableDescription(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetDescription(*s)
	}
	return auo
}

// ClearDescription clears the value of the "description" field.
func (auo *AgentUpdateOne) ClearDescription() *AgentUpdateOne {
	auo.mutation.ClearDescription()
	return auo
}

// SetInstructions sets the "instructions" field.
func (auo *AgentUpdateOne) SetInstructions(s string) *AgentUpdateOne {
	auo.mutation.SetInstructions(s)
	return auo
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableInstructions(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetInstructions(*s)
	}
	return auo
}

// SetModelID sets the "model" edge to the Model entity by ID.
func (auo *AgentUpdateOne) SetModelID(id uuid.UUID) *AgentUpdateOne {
	auo.mutation.SetModelID(id)
	return auo
}

// SetNillableModelID sets the "model" edge to the Model entity by ID if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableModelID(id *uuid.UUID) *AgentUpdateOne {
	if id != nil {
		auo = auo.SetModelID(*id)
	}
	return auo
}

// SetModel sets the "model" edge to the Model entity.
func (auo *AgentUpdateOne) SetModel(m *Model) *AgentUpdateOne {
	return auo.SetModelID(m.ID)
}

// AddDelegateIDs adds the "delegates" edge to the Agent entity by IDs.
func (auo *AgentUpdateOne) AddDelegateIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddDelegateIDs(ids...)
	return auo
}

// AddDelegates adds the "delegates" edges to the Agent entity.
func (auo *AgentUpdateOne) AddDelegates(a ...*Agent) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.AddDelegateIDs(ids...)
}

// AddDelegatorIDs adds the "delegators" edge to the Agent entity by IDs.
func (auo *AgentUpdateOne) AddDelegatorIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddDelegatorIDs(ids...)
	return auo
}

// AddDelegators adds the "delegators" edges to the Agent entity.
func (auo *AgentUpdateOne) AddDelegators(a ...*Agent) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.AddDelegatorIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (auo *AgentUpdateOne) Mutation() *AgentMutation {
	return auo.mutation
}

// ClearModel clears the "model" edge to the Model entity.
func (auo *AgentUpdateOne) ClearModel() *AgentUpdateOne {
	auo.mutation.ClearModel()
	return auo
}

// ClearDelegates clears all "delegates" edges to the Agent entity.
func (auo *AgentUpdateOne) ClearDelegates() *AgentUpdateOne {
	auo.mutation.ClearDelegates()
	return auo
}

// RemoveDelegateIDs removes the "delegates" edge to Agent entities by IDs.
func (auo *AgentUpdateOne) RemoveDelegateIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveDelegateIDs(ids...)
	return auo
}

// RemoveDelegates removes "delegates" edges to Agent entities.
func (auo *AgentUpdateOne) RemoveDelegates(a ...*Agent) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.RemoveDelegateIDs(ids...)
}

// ClearDelegators clears all "delegators" edges to the Agent entity.
func (auo *AgentUpdateOne) ClearDelegators() *AgentUpdateOne {
	auo.mutation.ClearDelegators()
	return auo
}

// RemoveDelegatorIDs removes the "delegators" edge to Agent entities by IDs.
func (auo *AgentUpdateOne) RemoveDelegatorIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveDelegatorIDs(ids...)
	return auo
}

// RemoveDelegators removes "delegators" edges to Agent entities.
func (auo *AgentUpdateOne) RemoveDelegators(a ...*Agent) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.RemoveDelegatorIDs(ids...)
}

// Where appends a list predicates to the AgentUpdate builder.
func (auo *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Agent entity.
func (auo *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AgentUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`memory: validator failed for field "Agent.name": %w`, err)}
		}
	}
	return nil
}

func (auo *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`memory: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.Description(); ok {
		_spec.SetField(agent.FieldDescription, field.TypeString, value)
	}
	if auo.mutation.DescriptionCleared() {
		_spec.ClearField(agent.FieldDescription, field.TypeString)
	}
	if value, ok := auo.mutation.Instructions(); ok {
		_spec.SetField(agent.FieldInstructions, field.TypeString, value)
	}
	if auo.mutation.ModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.ModelTable,
			Columns: []string{agent.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.ModelTable,
			Columns: []string{agent.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.DelegatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agent.DelegatesTable,
			Columns: agent.DelegatesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedDelegatesIDs(); len(nodes) > 0 && !auo.mutation.DelegatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agent.DelegatesTable,
			Columns: agent.DelegatesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.DelegatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agent.DelegatesTable,
			Columns: agent.DelegatesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.DelegatorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   agent.DelegatorsTable,
			Columns: agent.DelegatorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedDelegatorsIDs(); len(nodes) > 0 && !auo.mutation.DelegatorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   agent.DelegatorsTable,
			Columns: agent.DelegatorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.DelegatorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   agent.DelegatorsTable,
			Columns: agent.DelegatorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Agent{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
