//go:build ignore
// +build ignore

package main

import (
	"log/slog"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"github.com/hedwigz/entviz"
)

func main() {
	cfg := gen.Config{
		Header: "// Code generated by ent. DO NOT EDIT.",
	}

	if err := entc.Generate("./schema", &cfg, entc.Extensions(entviz.Extension{})); err != nil {
		slog.Error("running ent codegen", "error", err)
	}
}
