// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/furisto/construct/backend/memory/schema/types"
	"github.com/furisto/construct/backend/memory/task"
	"github.com/google/uuid"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetAgentID sets the "agent_id" field.
func (mu *MessageUpdate) SetAgentID(u uuid.UUID) *MessageUpdate {
	mu.mutation.SetAgentID(u)
	return mu
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableAgentID(u *uuid.UUID) *MessageUpdate {
	if u != nil {
		mu.SetAgentID(*u)
	}
	return mu
}

// SetUpdateTime sets the "update_time" field.
func (mu *MessageUpdate) SetUpdateTime(t time.Time) *MessageUpdate {
	mu.mutation.SetUpdateTime(t)
	return mu
}

// SetContent sets the "content" field.
func (mu *MessageUpdate) SetContent(tc *types.MessageContent) *MessageUpdate {
	mu.mutation.SetContent(tc)
	return mu
}

// SetRole sets the "role" field.
func (mu *MessageUpdate) SetRole(tr types.MessageRole) *MessageUpdate {
	mu.mutation.SetRole(tr)
	return mu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableRole(tr *types.MessageRole) *MessageUpdate {
	if tr != nil {
		mu.SetRole(*tr)
	}
	return mu
}

// SetUsage sets the "usage" field.
func (mu *MessageUpdate) SetUsage(tu *types.MessageUsage) *MessageUpdate {
	mu.mutation.SetUsage(tu)
	return mu
}

// ClearUsage clears the value of the "usage" field.
func (mu *MessageUpdate) ClearUsage() *MessageUpdate {
	mu.mutation.ClearUsage()
	return mu
}

// AddTaskIDs adds the "task" edge to the Task entity by IDs.
func (mu *MessageUpdate) AddTaskIDs(ids ...uuid.UUID) *MessageUpdate {
	mu.mutation.AddTaskIDs(ids...)
	return mu
}

// AddTask adds the "task" edges to the Task entity.
func (mu *MessageUpdate) AddTask(t ...*Task) *MessageUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return mu.AddTaskIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearTask clears all "task" edges to the Task entity.
func (mu *MessageUpdate) ClearTask() *MessageUpdate {
	mu.mutation.ClearTask()
	return mu
}

// RemoveTaskIDs removes the "task" edge to Task entities by IDs.
func (mu *MessageUpdate) RemoveTaskIDs(ids ...uuid.UUID) *MessageUpdate {
	mu.mutation.RemoveTaskIDs(ids...)
	return mu
}

// RemoveTask removes "task" edges to Task entities.
func (mu *MessageUpdate) RemoveTask(t ...*Task) *MessageUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return mu.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	mu.defaults()
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mu *MessageUpdate) defaults() {
	if _, ok := mu.mutation.UpdateTime(); !ok {
		v := message.UpdateDefaultUpdateTime()
		mu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`memory: validator failed for field "Message.role": %w`, err)}
		}
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.AgentID(); ok {
		_spec.SetField(message.FieldAgentID, field.TypeUUID, value)
	}
	if value, ok := mu.mutation.UpdateTime(); ok {
		_spec.SetField(message.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := mu.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeJSON, value)
	}
	if value, ok := mu.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeEnum, value)
	}
	if value, ok := mu.mutation.Usage(); ok {
		_spec.SetField(message.FieldUsage, field.TypeJSON, value)
	}
	if mu.mutation.UsageCleared() {
		_spec.ClearField(message.FieldUsage, field.TypeJSON)
	}
	if mu.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.TaskTable,
			Columns: message.TaskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedTaskIDs(); len(nodes) > 0 && !mu.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.TaskTable,
			Columns: message.TaskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.TaskTable,
			Columns: message.TaskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetAgentID sets the "agent_id" field.
func (muo *MessageUpdateOne) SetAgentID(u uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetAgentID(u)
	return muo
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableAgentID(u *uuid.UUID) *MessageUpdateOne {
	if u != nil {
		muo.SetAgentID(*u)
	}
	return muo
}

// SetUpdateTime sets the "update_time" field.
func (muo *MessageUpdateOne) SetUpdateTime(t time.Time) *MessageUpdateOne {
	muo.mutation.SetUpdateTime(t)
	return muo
}

// SetContent sets the "content" field.
func (muo *MessageUpdateOne) SetContent(tc *types.MessageContent) *MessageUpdateOne {
	muo.mutation.SetContent(tc)
	return muo
}

// SetRole sets the "role" field.
func (muo *MessageUpdateOne) SetRole(tr types.MessageRole) *MessageUpdateOne {
	muo.mutation.SetRole(tr)
	return muo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableRole(tr *types.MessageRole) *MessageUpdateOne {
	if tr != nil {
		muo.SetRole(*tr)
	}
	return muo
}

// SetUsage sets the "usage" field.
func (muo *MessageUpdateOne) SetUsage(tu *types.MessageUsage) *MessageUpdateOne {
	muo.mutation.SetUsage(tu)
	return muo
}

// ClearUsage clears the value of the "usage" field.
func (muo *MessageUpdateOne) ClearUsage() *MessageUpdateOne {
	muo.mutation.ClearUsage()
	return muo
}

// AddTaskIDs adds the "task" edge to the Task entity by IDs.
func (muo *MessageUpdateOne) AddTaskIDs(ids ...uuid.UUID) *MessageUpdateOne {
	muo.mutation.AddTaskIDs(ids...)
	return muo
}

// AddTask adds the "task" edges to the Task entity.
func (muo *MessageUpdateOne) AddTask(t ...*Task) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return muo.AddTaskIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearTask clears all "task" edges to the Task entity.
func (muo *MessageUpdateOne) ClearTask() *MessageUpdateOne {
	muo.mutation.ClearTask()
	return muo
}

// RemoveTaskIDs removes the "task" edge to Task entities by IDs.
func (muo *MessageUpdateOne) RemoveTaskIDs(ids ...uuid.UUID) *MessageUpdateOne {
	muo.mutation.RemoveTaskIDs(ids...)
	return muo
}

// RemoveTask removes "task" edges to Task entities.
func (muo *MessageUpdateOne) RemoveTask(t ...*Task) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return muo.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	muo.defaults()
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (muo *MessageUpdateOne) defaults() {
	if _, ok := muo.mutation.UpdateTime(); !ok {
		v := message.UpdateDefaultUpdateTime()
		muo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`memory: validator failed for field "Message.role": %w`, err)}
		}
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`memory: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.AgentID(); ok {
		_spec.SetField(message.FieldAgentID, field.TypeUUID, value)
	}
	if value, ok := muo.mutation.UpdateTime(); ok {
		_spec.SetField(message.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := muo.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeJSON, value)
	}
	if value, ok := muo.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeEnum, value)
	}
	if value, ok := muo.mutation.Usage(); ok {
		_spec.SetField(message.FieldUsage, field.TypeJSON, value)
	}
	if muo.mutation.UsageCleared() {
		_spec.ClearField(message.FieldUsage, field.TypeJSON)
	}
	if muo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.TaskTable,
			Columns: message.TaskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedTaskIDs(); len(nodes) > 0 && !muo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.TaskTable,
			Columns: message.TaskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.TaskTable,
			Columns: message.TaskPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
