// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/agent"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/model"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/furisto/construct/backend/memory/schema/types"
	"github.com/furisto/construct/backend/memory/task"
	"github.com/google/uuid"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks     []Hook
	mutation  *MessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetUpdateTime sets the "update_time" field.
func (mu *MessageUpdate) SetUpdateTime(t time.Time) *MessageUpdate {
	mu.mutation.SetUpdateTime(t)
	return mu
}

// SetSource sets the "source" field.
func (mu *MessageUpdate) SetSource(ts types.MessageSource) *MessageUpdate {
	mu.mutation.SetSource(ts)
	return mu
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableSource(ts *types.MessageSource) *MessageUpdate {
	if ts != nil {
		mu.SetSource(*ts)
	}
	return mu
}

// SetContent sets the "content" field.
func (mu *MessageUpdate) SetContent(tc *types.MessageContent) *MessageUpdate {
	mu.mutation.SetContent(tc)
	return mu
}

// SetUsage sets the "usage" field.
func (mu *MessageUpdate) SetUsage(tu *types.MessageUsage) *MessageUpdate {
	mu.mutation.SetUsage(tu)
	return mu
}

// ClearUsage clears the value of the "usage" field.
func (mu *MessageUpdate) ClearUsage() *MessageUpdate {
	mu.mutation.ClearUsage()
	return mu
}

// SetProcessedTime sets the "processed_time" field.
func (mu *MessageUpdate) SetProcessedTime(t time.Time) *MessageUpdate {
	mu.mutation.SetProcessedTime(t)
	return mu
}

// SetNillableProcessedTime sets the "processed_time" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableProcessedTime(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetProcessedTime(*t)
	}
	return mu
}

// ClearProcessedTime clears the value of the "processed_time" field.
func (mu *MessageUpdate) ClearProcessedTime() *MessageUpdate {
	mu.mutation.ClearProcessedTime()
	return mu
}

// SetTaskID sets the "task_id" field.
func (mu *MessageUpdate) SetTaskID(u uuid.UUID) *MessageUpdate {
	mu.mutation.SetTaskID(u)
	return mu
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableTaskID(u *uuid.UUID) *MessageUpdate {
	if u != nil {
		mu.SetTaskID(*u)
	}
	return mu
}

// SetAgentID sets the "agent_id" field.
func (mu *MessageUpdate) SetAgentID(u uuid.UUID) *MessageUpdate {
	mu.mutation.SetAgentID(u)
	return mu
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableAgentID(u *uuid.UUID) *MessageUpdate {
	if u != nil {
		mu.SetAgentID(*u)
	}
	return mu
}

// ClearAgentID clears the value of the "agent_id" field.
func (mu *MessageUpdate) ClearAgentID() *MessageUpdate {
	mu.mutation.ClearAgentID()
	return mu
}

// SetModelID sets the "model_id" field.
func (mu *MessageUpdate) SetModelID(u uuid.UUID) *MessageUpdate {
	mu.mutation.SetModelID(u)
	return mu
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableModelID(u *uuid.UUID) *MessageUpdate {
	if u != nil {
		mu.SetModelID(*u)
	}
	return mu
}

// ClearModelID clears the value of the "model_id" field.
func (mu *MessageUpdate) ClearModelID() *MessageUpdate {
	mu.mutation.ClearModelID()
	return mu
}

// SetTask sets the "task" edge to the Task entity.
func (mu *MessageUpdate) SetTask(t *Task) *MessageUpdate {
	return mu.SetTaskID(t.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (mu *MessageUpdate) SetAgent(a *Agent) *MessageUpdate {
	return mu.SetAgentID(a.ID)
}

// SetModel sets the "model" edge to the Model entity.
func (mu *MessageUpdate) SetModel(m *Model) *MessageUpdate {
	return mu.SetModelID(m.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (mu *MessageUpdate) ClearTask() *MessageUpdate {
	mu.mutation.ClearTask()
	return mu
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (mu *MessageUpdate) ClearAgent() *MessageUpdate {
	mu.mutation.ClearAgent()
	return mu
}

// ClearModel clears the "model" edge to the Model entity.
func (mu *MessageUpdate) ClearModel() *MessageUpdate {
	mu.mutation.ClearModel()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	mu.defaults()
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mu *MessageUpdate) defaults() {
	if _, ok := mu.mutation.UpdateTime(); !ok {
		v := message.UpdateDefaultUpdateTime()
		mu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.Source(); ok {
		if err := message.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`memory: validator failed for field "Message.source": %w`, err)}
		}
	}
	if mu.mutation.TaskCleared() && len(mu.mutation.TaskIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "Message.task"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (mu *MessageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MessageUpdate {
	mu.modifiers = append(mu.modifiers, modifiers...)
	return mu
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.UpdateTime(); ok {
		_spec.SetField(message.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := mu.mutation.Source(); ok {
		_spec.SetField(message.FieldSource, field.TypeEnum, value)
	}
	if value, ok := mu.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeJSON, value)
	}
	if value, ok := mu.mutation.Usage(); ok {
		_spec.SetField(message.FieldUsage, field.TypeJSON, value)
	}
	if mu.mutation.UsageCleared() {
		_spec.ClearField(message.FieldUsage, field.TypeJSON)
	}
	if value, ok := mu.mutation.ProcessedTime(); ok {
		_spec.SetField(message.FieldProcessedTime, field.TypeTime, value)
	}
	if mu.mutation.ProcessedTimeCleared() {
		_spec.ClearField(message.FieldProcessedTime, field.TypeTime)
	}
	if mu.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.TaskTable,
			Columns: []string{message.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.TaskTable,
			Columns: []string{message.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.AgentTable,
			Columns: []string{message.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.AgentTable,
			Columns: []string{message.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.ModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ModelTable,
			Columns: []string{message.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ModelTable,
			Columns: []string{message.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(mu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (muo *MessageUpdateOne) SetUpdateTime(t time.Time) *MessageUpdateOne {
	muo.mutation.SetUpdateTime(t)
	return muo
}

// SetSource sets the "source" field.
func (muo *MessageUpdateOne) SetSource(ts types.MessageSource) *MessageUpdateOne {
	muo.mutation.SetSource(ts)
	return muo
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableSource(ts *types.MessageSource) *MessageUpdateOne {
	if ts != nil {
		muo.SetSource(*ts)
	}
	return muo
}

// SetContent sets the "content" field.
func (muo *MessageUpdateOne) SetContent(tc *types.MessageContent) *MessageUpdateOne {
	muo.mutation.SetContent(tc)
	return muo
}

// SetUsage sets the "usage" field.
func (muo *MessageUpdateOne) SetUsage(tu *types.MessageUsage) *MessageUpdateOne {
	muo.mutation.SetUsage(tu)
	return muo
}

// ClearUsage clears the value of the "usage" field.
func (muo *MessageUpdateOne) ClearUsage() *MessageUpdateOne {
	muo.mutation.ClearUsage()
	return muo
}

// SetProcessedTime sets the "processed_time" field.
func (muo *MessageUpdateOne) SetProcessedTime(t time.Time) *MessageUpdateOne {
	muo.mutation.SetProcessedTime(t)
	return muo
}

// SetNillableProcessedTime sets the "processed_time" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableProcessedTime(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetProcessedTime(*t)
	}
	return muo
}

// ClearProcessedTime clears the value of the "processed_time" field.
func (muo *MessageUpdateOne) ClearProcessedTime() *MessageUpdateOne {
	muo.mutation.ClearProcessedTime()
	return muo
}

// SetTaskID sets the "task_id" field.
func (muo *MessageUpdateOne) SetTaskID(u uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetTaskID(u)
	return muo
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableTaskID(u *uuid.UUID) *MessageUpdateOne {
	if u != nil {
		muo.SetTaskID(*u)
	}
	return muo
}

// SetAgentID sets the "agent_id" field.
func (muo *MessageUpdateOne) SetAgentID(u uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetAgentID(u)
	return muo
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableAgentID(u *uuid.UUID) *MessageUpdateOne {
	if u != nil {
		muo.SetAgentID(*u)
	}
	return muo
}

// ClearAgentID clears the value of the "agent_id" field.
func (muo *MessageUpdateOne) ClearAgentID() *MessageUpdateOne {
	muo.mutation.ClearAgentID()
	return muo
}

// SetModelID sets the "model_id" field.
func (muo *MessageUpdateOne) SetModelID(u uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetModelID(u)
	return muo
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableModelID(u *uuid.UUID) *MessageUpdateOne {
	if u != nil {
		muo.SetModelID(*u)
	}
	return muo
}

// ClearModelID clears the value of the "model_id" field.
func (muo *MessageUpdateOne) ClearModelID() *MessageUpdateOne {
	muo.mutation.ClearModelID()
	return muo
}

// SetTask sets the "task" edge to the Task entity.
func (muo *MessageUpdateOne) SetTask(t *Task) *MessageUpdateOne {
	return muo.SetTaskID(t.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (muo *MessageUpdateOne) SetAgent(a *Agent) *MessageUpdateOne {
	return muo.SetAgentID(a.ID)
}

// SetModel sets the "model" edge to the Model entity.
func (muo *MessageUpdateOne) SetModel(m *Model) *MessageUpdateOne {
	return muo.SetModelID(m.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (muo *MessageUpdateOne) ClearTask() *MessageUpdateOne {
	muo.mutation.ClearTask()
	return muo
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (muo *MessageUpdateOne) ClearAgent() *MessageUpdateOne {
	muo.mutation.ClearAgent()
	return muo
}

// ClearModel clears the "model" edge to the Model entity.
func (muo *MessageUpdateOne) ClearModel() *MessageUpdateOne {
	muo.mutation.ClearModel()
	return muo
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	muo.defaults()
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (muo *MessageUpdateOne) defaults() {
	if _, ok := muo.mutation.UpdateTime(); !ok {
		v := message.UpdateDefaultUpdateTime()
		muo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.Source(); ok {
		if err := message.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`memory: validator failed for field "Message.source": %w`, err)}
		}
	}
	if muo.mutation.TaskCleared() && len(muo.mutation.TaskIDs()) > 0 {
		return errors.New(`memory: clearing a required unique edge "Message.task"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (muo *MessageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MessageUpdateOne {
	muo.modifiers = append(muo.modifiers, modifiers...)
	return muo
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`memory: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.UpdateTime(); ok {
		_spec.SetField(message.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := muo.mutation.Source(); ok {
		_spec.SetField(message.FieldSource, field.TypeEnum, value)
	}
	if value, ok := muo.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeJSON, value)
	}
	if value, ok := muo.mutation.Usage(); ok {
		_spec.SetField(message.FieldUsage, field.TypeJSON, value)
	}
	if muo.mutation.UsageCleared() {
		_spec.ClearField(message.FieldUsage, field.TypeJSON)
	}
	if value, ok := muo.mutation.ProcessedTime(); ok {
		_spec.SetField(message.FieldProcessedTime, field.TypeTime, value)
	}
	if muo.mutation.ProcessedTimeCleared() {
		_spec.ClearField(message.FieldProcessedTime, field.TypeTime)
	}
	if muo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.TaskTable,
			Columns: []string{message.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.TaskTable,
			Columns: []string{message.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.AgentTable,
			Columns: []string{message.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.AgentTable,
			Columns: []string{message.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.ModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ModelTable,
			Columns: []string{message.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.ModelTable,
			Columns: []string{message.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(muo.modifiers...)
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
