// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/model"
	"github.com/furisto/construct/backend/memory/modelprovider"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/google/uuid"
)

// ModelUpdate is the builder for updating Model entities.
type ModelUpdate struct {
	config
	hooks    []Hook
	mutation *ModelMutation
}

// Where appends a list predicates to the ModelUpdate builder.
func (mu *ModelUpdate) Where(ps ...predicate.Model) *ModelUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetName sets the "name" field.
func (mu *ModelUpdate) SetName(s string) *ModelUpdate {
	mu.mutation.SetName(s)
	return mu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mu *ModelUpdate) SetNillableName(s *string) *ModelUpdate {
	if s != nil {
		mu.SetName(*s)
	}
	return mu
}

// SetContextWindow sets the "context_window" field.
func (mu *ModelUpdate) SetContextWindow(i int64) *ModelUpdate {
	mu.mutation.ResetContextWindow()
	mu.mutation.SetContextWindow(i)
	return mu
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (mu *ModelUpdate) SetNillableContextWindow(i *int64) *ModelUpdate {
	if i != nil {
		mu.SetContextWindow(*i)
	}
	return mu
}

// AddContextWindow adds i to the "context_window" field.
func (mu *ModelUpdate) AddContextWindow(i int64) *ModelUpdate {
	mu.mutation.AddContextWindow(i)
	return mu
}

// SetEnabled sets the "enabled" field.
func (mu *ModelUpdate) SetEnabled(b bool) *ModelUpdate {
	mu.mutation.SetEnabled(b)
	return mu
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (mu *ModelUpdate) SetNillableEnabled(b *bool) *ModelUpdate {
	if b != nil {
		mu.SetEnabled(*b)
	}
	return mu
}

// SetModelProviderID sets the "model_provider" edge to the ModelProvider entity by ID.
func (mu *ModelUpdate) SetModelProviderID(id uuid.UUID) *ModelUpdate {
	mu.mutation.SetModelProviderID(id)
	return mu
}

// SetNillableModelProviderID sets the "model_provider" edge to the ModelProvider entity by ID if the given value is not nil.
func (mu *ModelUpdate) SetNillableModelProviderID(id *uuid.UUID) *ModelUpdate {
	if id != nil {
		mu = mu.SetModelProviderID(*id)
	}
	return mu
}

// SetModelProvider sets the "model_provider" edge to the ModelProvider entity.
func (mu *ModelUpdate) SetModelProvider(m *ModelProvider) *ModelUpdate {
	return mu.SetModelProviderID(m.ID)
}

// Mutation returns the ModelMutation object of the builder.
func (mu *ModelUpdate) Mutation() *ModelMutation {
	return mu.mutation
}

// ClearModelProvider clears the "model_provider" edge to the ModelProvider entity.
func (mu *ModelUpdate) ClearModelProvider() *ModelUpdate {
	mu.mutation.ClearModelProvider()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *ModelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *ModelUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *ModelUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *ModelUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *ModelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(model.Table, model.Columns, sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Name(); ok {
		_spec.SetField(model.FieldName, field.TypeString, value)
	}
	if value, ok := mu.mutation.ContextWindow(); ok {
		_spec.SetField(model.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.AddedContextWindow(); ok {
		_spec.AddField(model.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.Enabled(); ok {
		_spec.SetField(model.FieldEnabled, field.TypeBool, value)
	}
	if mu.mutation.ModelProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   model.ModelProviderTable,
			Columns: []string{model.ModelProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ModelProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   model.ModelProviderTable,
			Columns: []string{model.ModelProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{model.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// ModelUpdateOne is the builder for updating a single Model entity.
type ModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelMutation
}

// SetName sets the "name" field.
func (muo *ModelUpdateOne) SetName(s string) *ModelUpdateOne {
	muo.mutation.SetName(s)
	return muo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (muo *ModelUpdateOne) SetNillableName(s *string) *ModelUpdateOne {
	if s != nil {
		muo.SetName(*s)
	}
	return muo
}

// SetContextWindow sets the "context_window" field.
func (muo *ModelUpdateOne) SetContextWindow(i int64) *ModelUpdateOne {
	muo.mutation.ResetContextWindow()
	muo.mutation.SetContextWindow(i)
	return muo
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (muo *ModelUpdateOne) SetNillableContextWindow(i *int64) *ModelUpdateOne {
	if i != nil {
		muo.SetContextWindow(*i)
	}
	return muo
}

// AddContextWindow adds i to the "context_window" field.
func (muo *ModelUpdateOne) AddContextWindow(i int64) *ModelUpdateOne {
	muo.mutation.AddContextWindow(i)
	return muo
}

// SetEnabled sets the "enabled" field.
func (muo *ModelUpdateOne) SetEnabled(b bool) *ModelUpdateOne {
	muo.mutation.SetEnabled(b)
	return muo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (muo *ModelUpdateOne) SetNillableEnabled(b *bool) *ModelUpdateOne {
	if b != nil {
		muo.SetEnabled(*b)
	}
	return muo
}

// SetModelProviderID sets the "model_provider" edge to the ModelProvider entity by ID.
func (muo *ModelUpdateOne) SetModelProviderID(id uuid.UUID) *ModelUpdateOne {
	muo.mutation.SetModelProviderID(id)
	return muo
}

// SetNillableModelProviderID sets the "model_provider" edge to the ModelProvider entity by ID if the given value is not nil.
func (muo *ModelUpdateOne) SetNillableModelProviderID(id *uuid.UUID) *ModelUpdateOne {
	if id != nil {
		muo = muo.SetModelProviderID(*id)
	}
	return muo
}

// SetModelProvider sets the "model_provider" edge to the ModelProvider entity.
func (muo *ModelUpdateOne) SetModelProvider(m *ModelProvider) *ModelUpdateOne {
	return muo.SetModelProviderID(m.ID)
}

// Mutation returns the ModelMutation object of the builder.
func (muo *ModelUpdateOne) Mutation() *ModelMutation {
	return muo.mutation
}

// ClearModelProvider clears the "model_provider" edge to the ModelProvider entity.
func (muo *ModelUpdateOne) ClearModelProvider() *ModelUpdateOne {
	muo.mutation.ClearModelProvider()
	return muo
}

// Where appends a list predicates to the ModelUpdate builder.
func (muo *ModelUpdateOne) Where(ps ...predicate.Model) *ModelUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *ModelUpdateOne) Select(field string, fields ...string) *ModelUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Model entity.
func (muo *ModelUpdateOne) Save(ctx context.Context) (*Model, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *ModelUpdateOne) SaveX(ctx context.Context) *Model {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *ModelUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *ModelUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *ModelUpdateOne) sqlSave(ctx context.Context) (_node *Model, err error) {
	_spec := sqlgraph.NewUpdateSpec(model.Table, model.Columns, sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`memory: missing "Model.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, model.FieldID)
		for _, f := range fields {
			if !model.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
			}
			if f != model.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Name(); ok {
		_spec.SetField(model.FieldName, field.TypeString, value)
	}
	if value, ok := muo.mutation.ContextWindow(); ok {
		_spec.SetField(model.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.AddedContextWindow(); ok {
		_spec.AddField(model.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.Enabled(); ok {
		_spec.SetField(model.FieldEnabled, field.TypeBool, value)
	}
	if muo.mutation.ModelProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   model.ModelProviderTable,
			Columns: []string{model.ModelProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ModelProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   model.ModelProviderTable,
			Columns: []string{model.ModelProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Model{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{model.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
