// Code generated by ent. DO NOT EDIT.

package memory

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/furisto/construct/backend/memory/model"
	"github.com/furisto/construct/backend/memory/modelprovider"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/furisto/construct/backend/memory/schema/types"
	"github.com/google/uuid"
)

// ModelProviderUpdate is the builder for updating ModelProvider entities.
type ModelProviderUpdate struct {
	config
	hooks    []Hook
	mutation *ModelProviderMutation
}

// Where appends a list predicates to the ModelProviderUpdate builder.
func (mpu *ModelProviderUpdate) Where(ps ...predicate.ModelProvider) *ModelProviderUpdate {
	mpu.mutation.Where(ps...)
	return mpu
}

// SetUpdateTime sets the "update_time" field.
func (mpu *ModelProviderUpdate) SetUpdateTime(t time.Time) *ModelProviderUpdate {
	mpu.mutation.SetUpdateTime(t)
	return mpu
}

// SetName sets the "name" field.
func (mpu *ModelProviderUpdate) SetName(s string) *ModelProviderUpdate {
	mpu.mutation.SetName(s)
	return mpu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mpu *ModelProviderUpdate) SetNillableName(s *string) *ModelProviderUpdate {
	if s != nil {
		mpu.SetName(*s)
	}
	return mpu
}

// SetProviderType sets the "provider_type" field.
func (mpu *ModelProviderUpdate) SetProviderType(tpt types.ModelProviderType) *ModelProviderUpdate {
	mpu.mutation.SetProviderType(tpt)
	return mpu
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (mpu *ModelProviderUpdate) SetNillableProviderType(tpt *types.ModelProviderType) *ModelProviderUpdate {
	if tpt != nil {
		mpu.SetProviderType(*tpt)
	}
	return mpu
}

// SetURL sets the "url" field.
func (mpu *ModelProviderUpdate) SetURL(s string) *ModelProviderUpdate {
	mpu.mutation.SetURL(s)
	return mpu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (mpu *ModelProviderUpdate) SetNillableURL(s *string) *ModelProviderUpdate {
	if s != nil {
		mpu.SetURL(*s)
	}
	return mpu
}

// SetSecret sets the "secret" field.
func (mpu *ModelProviderUpdate) SetSecret(b []byte) *ModelProviderUpdate {
	mpu.mutation.SetSecret(b)
	return mpu
}

// SetEnabled sets the "enabled" field.
func (mpu *ModelProviderUpdate) SetEnabled(b bool) *ModelProviderUpdate {
	mpu.mutation.SetEnabled(b)
	return mpu
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (mpu *ModelProviderUpdate) SetNillableEnabled(b *bool) *ModelProviderUpdate {
	if b != nil {
		mpu.SetEnabled(*b)
	}
	return mpu
}

// AddModelIDs adds the "models" edge to the Model entity by IDs.
func (mpu *ModelProviderUpdate) AddModelIDs(ids ...uuid.UUID) *ModelProviderUpdate {
	mpu.mutation.AddModelIDs(ids...)
	return mpu
}

// AddModels adds the "models" edges to the Model entity.
func (mpu *ModelProviderUpdate) AddModels(m ...*Model) *ModelProviderUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mpu.AddModelIDs(ids...)
}

// Mutation returns the ModelProviderMutation object of the builder.
func (mpu *ModelProviderUpdate) Mutation() *ModelProviderMutation {
	return mpu.mutation
}

// ClearModels clears all "models" edges to the Model entity.
func (mpu *ModelProviderUpdate) ClearModels() *ModelProviderUpdate {
	mpu.mutation.ClearModels()
	return mpu
}

// RemoveModelIDs removes the "models" edge to Model entities by IDs.
func (mpu *ModelProviderUpdate) RemoveModelIDs(ids ...uuid.UUID) *ModelProviderUpdate {
	mpu.mutation.RemoveModelIDs(ids...)
	return mpu
}

// RemoveModels removes "models" edges to Model entities.
func (mpu *ModelProviderUpdate) RemoveModels(m ...*Model) *ModelProviderUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mpu.RemoveModelIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mpu *ModelProviderUpdate) Save(ctx context.Context) (int, error) {
	mpu.defaults()
	return withHooks(ctx, mpu.sqlSave, mpu.mutation, mpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mpu *ModelProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := mpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mpu *ModelProviderUpdate) Exec(ctx context.Context) error {
	_, err := mpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpu *ModelProviderUpdate) ExecX(ctx context.Context) {
	if err := mpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mpu *ModelProviderUpdate) defaults() {
	if _, ok := mpu.mutation.UpdateTime(); !ok {
		v := modelprovider.UpdateDefaultUpdateTime()
		mpu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpu *ModelProviderUpdate) check() error {
	if v, ok := mpu.mutation.Name(); ok {
		if err := modelprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.name": %w`, err)}
		}
	}
	if v, ok := mpu.mutation.ProviderType(); ok {
		if err := modelprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.provider_type": %w`, err)}
		}
	}
	if v, ok := mpu.mutation.URL(); ok {
		if err := modelprovider.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.url": %w`, err)}
		}
	}
	if v, ok := mpu.mutation.Secret(); ok {
		if err := modelprovider.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.secret": %w`, err)}
		}
	}
	return nil
}

func (mpu *ModelProviderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelprovider.Table, modelprovider.Columns, sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID))
	if ps := mpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mpu.mutation.UpdateTime(); ok {
		_spec.SetField(modelprovider.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := mpu.mutation.Name(); ok {
		_spec.SetField(modelprovider.FieldName, field.TypeString, value)
	}
	if value, ok := mpu.mutation.ProviderType(); ok {
		_spec.SetField(modelprovider.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := mpu.mutation.URL(); ok {
		_spec.SetField(modelprovider.FieldURL, field.TypeString, value)
	}
	if value, ok := mpu.mutation.Secret(); ok {
		_spec.SetField(modelprovider.FieldSecret, field.TypeBytes, value)
	}
	if value, ok := mpu.mutation.Enabled(); ok {
		_spec.SetField(modelprovider.FieldEnabled, field.TypeBool, value)
	}
	if mpu.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelprovider.ModelsTable,
			Columns: []string{modelprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mpu.mutation.RemovedModelsIDs(); len(nodes) > 0 && !mpu.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelprovider.ModelsTable,
			Columns: []string{modelprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mpu.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelprovider.ModelsTable,
			Columns: []string{modelprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mpu.mutation.done = true
	return n, nil
}

// ModelProviderUpdateOne is the builder for updating a single ModelProvider entity.
type ModelProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelProviderMutation
}

// SetUpdateTime sets the "update_time" field.
func (mpuo *ModelProviderUpdateOne) SetUpdateTime(t time.Time) *ModelProviderUpdateOne {
	mpuo.mutation.SetUpdateTime(t)
	return mpuo
}

// SetName sets the "name" field.
func (mpuo *ModelProviderUpdateOne) SetName(s string) *ModelProviderUpdateOne {
	mpuo.mutation.SetName(s)
	return mpuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mpuo *ModelProviderUpdateOne) SetNillableName(s *string) *ModelProviderUpdateOne {
	if s != nil {
		mpuo.SetName(*s)
	}
	return mpuo
}

// SetProviderType sets the "provider_type" field.
func (mpuo *ModelProviderUpdateOne) SetProviderType(tpt types.ModelProviderType) *ModelProviderUpdateOne {
	mpuo.mutation.SetProviderType(tpt)
	return mpuo
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (mpuo *ModelProviderUpdateOne) SetNillableProviderType(tpt *types.ModelProviderType) *ModelProviderUpdateOne {
	if tpt != nil {
		mpuo.SetProviderType(*tpt)
	}
	return mpuo
}

// SetURL sets the "url" field.
func (mpuo *ModelProviderUpdateOne) SetURL(s string) *ModelProviderUpdateOne {
	mpuo.mutation.SetURL(s)
	return mpuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (mpuo *ModelProviderUpdateOne) SetNillableURL(s *string) *ModelProviderUpdateOne {
	if s != nil {
		mpuo.SetURL(*s)
	}
	return mpuo
}

// SetSecret sets the "secret" field.
func (mpuo *ModelProviderUpdateOne) SetSecret(b []byte) *ModelProviderUpdateOne {
	mpuo.mutation.SetSecret(b)
	return mpuo
}

// SetEnabled sets the "enabled" field.
func (mpuo *ModelProviderUpdateOne) SetEnabled(b bool) *ModelProviderUpdateOne {
	mpuo.mutation.SetEnabled(b)
	return mpuo
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (mpuo *ModelProviderUpdateOne) SetNillableEnabled(b *bool) *ModelProviderUpdateOne {
	if b != nil {
		mpuo.SetEnabled(*b)
	}
	return mpuo
}

// AddModelIDs adds the "models" edge to the Model entity by IDs.
func (mpuo *ModelProviderUpdateOne) AddModelIDs(ids ...uuid.UUID) *ModelProviderUpdateOne {
	mpuo.mutation.AddModelIDs(ids...)
	return mpuo
}

// AddModels adds the "models" edges to the Model entity.
func (mpuo *ModelProviderUpdateOne) AddModels(m ...*Model) *ModelProviderUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mpuo.AddModelIDs(ids...)
}

// Mutation returns the ModelProviderMutation object of the builder.
func (mpuo *ModelProviderUpdateOne) Mutation() *ModelProviderMutation {
	return mpuo.mutation
}

// ClearModels clears all "models" edges to the Model entity.
func (mpuo *ModelProviderUpdateOne) ClearModels() *ModelProviderUpdateOne {
	mpuo.mutation.ClearModels()
	return mpuo
}

// RemoveModelIDs removes the "models" edge to Model entities by IDs.
func (mpuo *ModelProviderUpdateOne) RemoveModelIDs(ids ...uuid.UUID) *ModelProviderUpdateOne {
	mpuo.mutation.RemoveModelIDs(ids...)
	return mpuo
}

// RemoveModels removes "models" edges to Model entities.
func (mpuo *ModelProviderUpdateOne) RemoveModels(m ...*Model) *ModelProviderUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mpuo.RemoveModelIDs(ids...)
}

// Where appends a list predicates to the ModelProviderUpdate builder.
func (mpuo *ModelProviderUpdateOne) Where(ps ...predicate.ModelProvider) *ModelProviderUpdateOne {
	mpuo.mutation.Where(ps...)
	return mpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mpuo *ModelProviderUpdateOne) Select(field string, fields ...string) *ModelProviderUpdateOne {
	mpuo.fields = append([]string{field}, fields...)
	return mpuo
}

// Save executes the query and returns the updated ModelProvider entity.
func (mpuo *ModelProviderUpdateOne) Save(ctx context.Context) (*ModelProvider, error) {
	mpuo.defaults()
	return withHooks(ctx, mpuo.sqlSave, mpuo.mutation, mpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mpuo *ModelProviderUpdateOne) SaveX(ctx context.Context) *ModelProvider {
	node, err := mpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mpuo *ModelProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := mpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpuo *ModelProviderUpdateOne) ExecX(ctx context.Context) {
	if err := mpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mpuo *ModelProviderUpdateOne) defaults() {
	if _, ok := mpuo.mutation.UpdateTime(); !ok {
		v := modelprovider.UpdateDefaultUpdateTime()
		mpuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mpuo *ModelProviderUpdateOne) check() error {
	if v, ok := mpuo.mutation.Name(); ok {
		if err := modelprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.name": %w`, err)}
		}
	}
	if v, ok := mpuo.mutation.ProviderType(); ok {
		if err := modelprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.provider_type": %w`, err)}
		}
	}
	if v, ok := mpuo.mutation.URL(); ok {
		if err := modelprovider.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.url": %w`, err)}
		}
	}
	if v, ok := mpuo.mutation.Secret(); ok {
		if err := modelprovider.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`memory: validator failed for field "ModelProvider.secret": %w`, err)}
		}
	}
	return nil
}

func (mpuo *ModelProviderUpdateOne) sqlSave(ctx context.Context) (_node *ModelProvider, err error) {
	if err := mpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelprovider.Table, modelprovider.Columns, sqlgraph.NewFieldSpec(modelprovider.FieldID, field.TypeUUID))
	id, ok := mpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`memory: missing "ModelProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelprovider.FieldID)
		for _, f := range fields {
			if !modelprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("memory: invalid field %q for query", f)}
			}
			if f != modelprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mpuo.mutation.UpdateTime(); ok {
		_spec.SetField(modelprovider.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := mpuo.mutation.Name(); ok {
		_spec.SetField(modelprovider.FieldName, field.TypeString, value)
	}
	if value, ok := mpuo.mutation.ProviderType(); ok {
		_spec.SetField(modelprovider.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := mpuo.mutation.URL(); ok {
		_spec.SetField(modelprovider.FieldURL, field.TypeString, value)
	}
	if value, ok := mpuo.mutation.Secret(); ok {
		_spec.SetField(modelprovider.FieldSecret, field.TypeBytes, value)
	}
	if value, ok := mpuo.mutation.Enabled(); ok {
		_spec.SetField(modelprovider.FieldEnabled, field.TypeBool, value)
	}
	if mpuo.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelprovider.ModelsTable,
			Columns: []string{modelprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mpuo.mutation.RemovedModelsIDs(); len(nodes) > 0 && !mpuo.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelprovider.ModelsTable,
			Columns: []string{modelprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mpuo.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelprovider.ModelsTable,
			Columns: []string{modelprovider.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(model.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ModelProvider{config: mpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mpuo.mutation.done = true
	return _node, nil
}
