// Code generated by ent. DO NOT EDIT.

package memory

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/furisto/construct/backend/memory/modelprovider"
	"github.com/furisto/construct/backend/memory/schema/types"
	"github.com/google/uuid"
)

// ModelProvider is the model entity for the ModelProvider schema.
type ModelProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ProviderType holds the value of the "provider_type" field.
	ProviderType types.ModelProviderType `json:"provider_type,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Secret holds the value of the "secret" field.
	Secret []byte `json:"-"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelProviderQuery when eager-loading is set.
	Edges        ModelProviderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelProviderEdges holds the relations/edges for other nodes in the graph.
type ModelProviderEdges struct {
	// Models holds the value of the models edge.
	Models []*Model `json:"models,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ModelsOrErr returns the Models value or an error if the edge
// was not loaded in eager-loading.
func (e ModelProviderEdges) ModelsOrErr() ([]*Model, error) {
	if e.loadedTypes[0] {
		return e.Models, nil
	}
	return nil, &NotLoadedError{edge: "models"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelprovider.FieldSecret:
			values[i] = new([]byte)
		case modelprovider.FieldEnabled:
			values[i] = new(sql.NullBool)
		case modelprovider.FieldName, modelprovider.FieldProviderType, modelprovider.FieldURL:
			values[i] = new(sql.NullString)
		case modelprovider.FieldCreateTime, modelprovider.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case modelprovider.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelProvider fields.
func (mp *ModelProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelprovider.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mp.ID = *value
			}
		case modelprovider.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				mp.CreateTime = value.Time
			}
		case modelprovider.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				mp.UpdateTime = value.Time
			}
		case modelprovider.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				mp.Name = value.String
			}
		case modelprovider.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				mp.ProviderType = types.ModelProviderType(value.String)
			}
		case modelprovider.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				mp.URL = value.String
			}
		case modelprovider.FieldSecret:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secret", values[i])
			} else if value != nil {
				mp.Secret = *value
			}
		case modelprovider.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				mp.Enabled = value.Bool
			}
		default:
			mp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelProvider.
// This includes values selected through modifiers, order, etc.
func (mp *ModelProvider) Value(name string) (ent.Value, error) {
	return mp.selectValues.Get(name)
}

// QueryModels queries the "models" edge of the ModelProvider entity.
func (mp *ModelProvider) QueryModels() *ModelQuery {
	return NewModelProviderClient(mp.config).QueryModels(mp)
}

// Update returns a builder for updating this ModelProvider.
// Note that you need to call ModelProvider.Unwrap() before calling this method if this ModelProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (mp *ModelProvider) Update() *ModelProviderUpdateOne {
	return NewModelProviderClient(mp.config).UpdateOne(mp)
}

// Unwrap unwraps the ModelProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mp *ModelProvider) Unwrap() *ModelProvider {
	_tx, ok := mp.config.driver.(*txDriver)
	if !ok {
		panic("memory: ModelProvider is not a transactional entity")
	}
	mp.config.driver = _tx.drv
	return mp
}

// String implements the fmt.Stringer.
func (mp *ModelProvider) String() string {
	var builder strings.Builder
	builder.WriteString("ModelProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mp.ID))
	builder.WriteString("create_time=")
	builder.WriteString(mp.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(mp.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(mp.Name)
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(fmt.Sprintf("%v", mp.ProviderType))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(mp.URL)
	builder.WriteString(", ")
	builder.WriteString("secret=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", mp.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// ModelProviders is a parsable slice of ModelProvider.
type ModelProviders []*ModelProvider
