// Code generated by ent. DO NOT EDIT.

package memory

import (
	"time"

	"github.com/furisto/construct/backend/memory/agent"
	"github.com/furisto/construct/backend/memory/message"
	"github.com/furisto/construct/backend/memory/model"
	"github.com/furisto/construct/backend/memory/modelprovider"
	"github.com/furisto/construct/backend/memory/schema"
	"github.com/furisto/construct/backend/memory/task"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescName is the schema descriptor for name field.
	agentDescName := agentFields[1].Descriptor()
	// agent.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agent.NameValidator = agentDescName.Validators[0].(func(string) error)
	// agentDescID is the schema descriptor for id field.
	agentDescID := agentFields[0].Descriptor()
	// agent.DefaultID holds the default value on creation for the id field.
	agent.DefaultID = agentDescID.Default.(func() uuid.UUID)
	messageMixin := schema.Message{}.Mixin()
	messageMixinFields1 := messageMixin[1].Fields()
	_ = messageMixinFields1
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreateTime is the schema descriptor for create_time field.
	messageDescCreateTime := messageMixinFields1[0].Descriptor()
	// message.DefaultCreateTime holds the default value on creation for the create_time field.
	message.DefaultCreateTime = messageDescCreateTime.Default.(func() time.Time)
	// messageDescUpdateTime is the schema descriptor for update_time field.
	messageDescUpdateTime := messageMixinFields1[1].Descriptor()
	// message.DefaultUpdateTime holds the default value on creation for the update_time field.
	message.DefaultUpdateTime = messageDescUpdateTime.Default.(func() time.Time)
	// message.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	message.UpdateDefaultUpdateTime = messageDescUpdateTime.UpdateDefault.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	modelFields := schema.Model{}.Fields()
	_ = modelFields
	// modelDescInputCost is the schema descriptor for input_cost field.
	modelDescInputCost := modelFields[4].Descriptor()
	// model.DefaultInputCost holds the default value on creation for the input_cost field.
	model.DefaultInputCost = modelDescInputCost.Default.(float64)
	// model.InputCostValidator is a validator for the "input_cost" field. It is called by the builders before save.
	model.InputCostValidator = modelDescInputCost.Validators[0].(func(float64) error)
	// modelDescOutputCost is the schema descriptor for output_cost field.
	modelDescOutputCost := modelFields[5].Descriptor()
	// model.DefaultOutputCost holds the default value on creation for the output_cost field.
	model.DefaultOutputCost = modelDescOutputCost.Default.(float64)
	// model.OutputCostValidator is a validator for the "output_cost" field. It is called by the builders before save.
	model.OutputCostValidator = modelDescOutputCost.Validators[0].(func(float64) error)
	// modelDescCacheWriteCost is the schema descriptor for cache_write_cost field.
	modelDescCacheWriteCost := modelFields[6].Descriptor()
	// model.DefaultCacheWriteCost holds the default value on creation for the cache_write_cost field.
	model.DefaultCacheWriteCost = modelDescCacheWriteCost.Default.(float64)
	// model.CacheWriteCostValidator is a validator for the "cache_write_cost" field. It is called by the builders before save.
	model.CacheWriteCostValidator = modelDescCacheWriteCost.Validators[0].(func(float64) error)
	// modelDescCacheReadCost is the schema descriptor for cache_read_cost field.
	modelDescCacheReadCost := modelFields[7].Descriptor()
	// model.DefaultCacheReadCost holds the default value on creation for the cache_read_cost field.
	model.DefaultCacheReadCost = modelDescCacheReadCost.Default.(float64)
	// model.CacheReadCostValidator is a validator for the "cache_read_cost" field. It is called by the builders before save.
	model.CacheReadCostValidator = modelDescCacheReadCost.Validators[0].(func(float64) error)
	// modelDescEnabled is the schema descriptor for enabled field.
	modelDescEnabled := modelFields[8].Descriptor()
	// model.DefaultEnabled holds the default value on creation for the enabled field.
	model.DefaultEnabled = modelDescEnabled.Default.(bool)
	// modelDescID is the schema descriptor for id field.
	modelDescID := modelFields[0].Descriptor()
	// model.DefaultID holds the default value on creation for the id field.
	model.DefaultID = modelDescID.Default.(func() uuid.UUID)
	modelproviderMixin := schema.ModelProvider{}.Mixin()
	modelproviderMixinFields0 := modelproviderMixin[0].Fields()
	_ = modelproviderMixinFields0
	modelproviderFields := schema.ModelProvider{}.Fields()
	_ = modelproviderFields
	// modelproviderDescCreateTime is the schema descriptor for create_time field.
	modelproviderDescCreateTime := modelproviderMixinFields0[0].Descriptor()
	// modelprovider.DefaultCreateTime holds the default value on creation for the create_time field.
	modelprovider.DefaultCreateTime = modelproviderDescCreateTime.Default.(func() time.Time)
	// modelproviderDescUpdateTime is the schema descriptor for update_time field.
	modelproviderDescUpdateTime := modelproviderMixinFields0[1].Descriptor()
	// modelprovider.DefaultUpdateTime holds the default value on creation for the update_time field.
	modelprovider.DefaultUpdateTime = modelproviderDescUpdateTime.Default.(func() time.Time)
	// modelprovider.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	modelprovider.UpdateDefaultUpdateTime = modelproviderDescUpdateTime.UpdateDefault.(func() time.Time)
	// modelproviderDescName is the schema descriptor for name field.
	modelproviderDescName := modelproviderFields[1].Descriptor()
	// modelprovider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	modelprovider.NameValidator = modelproviderDescName.Validators[0].(func(string) error)
	// modelproviderDescSecret is the schema descriptor for secret field.
	modelproviderDescSecret := modelproviderFields[4].Descriptor()
	// modelprovider.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	modelprovider.SecretValidator = modelproviderDescSecret.Validators[0].(func([]byte) error)
	// modelproviderDescEnabled is the schema descriptor for enabled field.
	modelproviderDescEnabled := modelproviderFields[5].Descriptor()
	// modelprovider.DefaultEnabled holds the default value on creation for the enabled field.
	modelprovider.DefaultEnabled = modelproviderDescEnabled.Default.(bool)
	// modelproviderDescID is the schema descriptor for id field.
	modelproviderDescID := modelproviderFields[0].Descriptor()
	// modelprovider.DefaultID holds the default value on creation for the id field.
	modelprovider.DefaultID = modelproviderDescID.Default.(func() uuid.UUID)
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields1 := taskMixin[1].Fields()
	_ = taskMixinFields1
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreateTime is the schema descriptor for create_time field.
	taskDescCreateTime := taskMixinFields1[0].Descriptor()
	// task.DefaultCreateTime holds the default value on creation for the create_time field.
	task.DefaultCreateTime = taskDescCreateTime.Default.(func() time.Time)
	// taskDescUpdateTime is the schema descriptor for update_time field.
	taskDescUpdateTime := taskMixinFields1[1].Descriptor()
	// task.DefaultUpdateTime holds the default value on creation for the update_time field.
	task.DefaultUpdateTime = taskDescUpdateTime.Default.(func() time.Time)
	// task.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	task.UpdateDefaultUpdateTime = taskDescUpdateTime.UpdateDefault.(func() time.Time)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
}
