// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: construct/v1/modelprovider.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/furisto/construct/api/go/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ModelProviderServiceName is the fully-qualified name of the ModelProviderService service.
	ModelProviderServiceName = "construct.v1.ModelProviderService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ModelProviderServiceCreateProviderProcedure is the fully-qualified name of the
	// ModelProviderService's CreateProvider RPC.
	ModelProviderServiceCreateProviderProcedure = "/construct.v1.ModelProviderService/CreateProvider"
	// ModelProviderServiceGetProviderProcedure is the fully-qualified name of the
	// ModelProviderService's GetProvider RPC.
	ModelProviderServiceGetProviderProcedure = "/construct.v1.ModelProviderService/GetProvider"
	// ModelProviderServiceListProvidersProcedure is the fully-qualified name of the
	// ModelProviderService's ListProviders RPC.
	ModelProviderServiceListProvidersProcedure = "/construct.v1.ModelProviderService/ListProviders"
	// ModelProviderServiceUpdateProviderProcedure is the fully-qualified name of the
	// ModelProviderService's UpdateProvider RPC.
	ModelProviderServiceUpdateProviderProcedure = "/construct.v1.ModelProviderService/UpdateProvider"
	// ModelProviderServiceDeleteProviderProcedure is the fully-qualified name of the
	// ModelProviderService's DeleteProvider RPC.
	ModelProviderServiceDeleteProviderProcedure = "/construct.v1.ModelProviderService/DeleteProvider"
)

// ModelProviderServiceClient is a client for the construct.v1.ModelProviderService service.
type ModelProviderServiceClient interface {
	CreateProvider(context.Context, *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error)
	GetProvider(context.Context, *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error)
	ListProviders(context.Context, *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error)
	UpdateProvider(context.Context, *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error)
	DeleteProvider(context.Context, *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error)
}

// NewModelProviderServiceClient constructs a client for the construct.v1.ModelProviderService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModelProviderServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModelProviderServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	modelProviderServiceMethods := v1.File_construct_v1_modelprovider_proto.Services().ByName("ModelProviderService").Methods()
	return &modelProviderServiceClient{
		createProvider: connect.NewClient[v1.CreateModelProviderRequest, v1.CreateModelProviderResponse](
			httpClient,
			baseURL+ModelProviderServiceCreateProviderProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("CreateProvider")),
			connect.WithClientOptions(opts...),
		),
		getProvider: connect.NewClient[v1.GetModelProviderRequest, v1.GetModelProviderResponse](
			httpClient,
			baseURL+ModelProviderServiceGetProviderProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("GetProvider")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listProviders: connect.NewClient[v1.ListModelProvidersRequest, v1.ListModelProvidersResponse](
			httpClient,
			baseURL+ModelProviderServiceListProvidersProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("ListProviders")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateProvider: connect.NewClient[v1.UpdateModelProviderRequest, v1.UpdateModelProviderResponse](
			httpClient,
			baseURL+ModelProviderServiceUpdateProviderProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("UpdateProvider")),
			connect.WithClientOptions(opts...),
		),
		deleteProvider: connect.NewClient[v1.DeleteModelProviderRequest, v1.DeleteModelProviderResponse](
			httpClient,
			baseURL+ModelProviderServiceDeleteProviderProcedure,
			connect.WithSchema(modelProviderServiceMethods.ByName("DeleteProvider")),
			connect.WithClientOptions(opts...),
		),
	}
}

// modelProviderServiceClient implements ModelProviderServiceClient.
type modelProviderServiceClient struct {
	createProvider *connect.Client[v1.CreateModelProviderRequest, v1.CreateModelProviderResponse]
	getProvider    *connect.Client[v1.GetModelProviderRequest, v1.GetModelProviderResponse]
	listProviders  *connect.Client[v1.ListModelProvidersRequest, v1.ListModelProvidersResponse]
	updateProvider *connect.Client[v1.UpdateModelProviderRequest, v1.UpdateModelProviderResponse]
	deleteProvider *connect.Client[v1.DeleteModelProviderRequest, v1.DeleteModelProviderResponse]
}

// CreateProvider calls construct.v1.ModelProviderService.CreateProvider.
func (c *modelProviderServiceClient) CreateProvider(ctx context.Context, req *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error) {
	return c.createProvider.CallUnary(ctx, req)
}

// GetProvider calls construct.v1.ModelProviderService.GetProvider.
func (c *modelProviderServiceClient) GetProvider(ctx context.Context, req *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error) {
	return c.getProvider.CallUnary(ctx, req)
}

// ListProviders calls construct.v1.ModelProviderService.ListProviders.
func (c *modelProviderServiceClient) ListProviders(ctx context.Context, req *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error) {
	return c.listProviders.CallUnary(ctx, req)
}

// UpdateProvider calls construct.v1.ModelProviderService.UpdateProvider.
func (c *modelProviderServiceClient) UpdateProvider(ctx context.Context, req *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error) {
	return c.updateProvider.CallUnary(ctx, req)
}

// DeleteProvider calls construct.v1.ModelProviderService.DeleteProvider.
func (c *modelProviderServiceClient) DeleteProvider(ctx context.Context, req *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error) {
	return c.deleteProvider.CallUnary(ctx, req)
}

// ModelProviderServiceHandler is an implementation of the construct.v1.ModelProviderService
// service.
type ModelProviderServiceHandler interface {
	CreateProvider(context.Context, *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error)
	GetProvider(context.Context, *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error)
	ListProviders(context.Context, *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error)
	UpdateProvider(context.Context, *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error)
	DeleteProvider(context.Context, *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error)
}

// NewModelProviderServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModelProviderServiceHandler(svc ModelProviderServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	modelProviderServiceMethods := v1.File_construct_v1_modelprovider_proto.Services().ByName("ModelProviderService").Methods()
	modelProviderServiceCreateProviderHandler := connect.NewUnaryHandler(
		ModelProviderServiceCreateProviderProcedure,
		svc.CreateProvider,
		connect.WithSchema(modelProviderServiceMethods.ByName("CreateProvider")),
		connect.WithHandlerOptions(opts...),
	)
	modelProviderServiceGetProviderHandler := connect.NewUnaryHandler(
		ModelProviderServiceGetProviderProcedure,
		svc.GetProvider,
		connect.WithSchema(modelProviderServiceMethods.ByName("GetProvider")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modelProviderServiceListProvidersHandler := connect.NewUnaryHandler(
		ModelProviderServiceListProvidersProcedure,
		svc.ListProviders,
		connect.WithSchema(modelProviderServiceMethods.ByName("ListProviders")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	modelProviderServiceUpdateProviderHandler := connect.NewUnaryHandler(
		ModelProviderServiceUpdateProviderProcedure,
		svc.UpdateProvider,
		connect.WithSchema(modelProviderServiceMethods.ByName("UpdateProvider")),
		connect.WithHandlerOptions(opts...),
	)
	modelProviderServiceDeleteProviderHandler := connect.NewUnaryHandler(
		ModelProviderServiceDeleteProviderProcedure,
		svc.DeleteProvider,
		connect.WithSchema(modelProviderServiceMethods.ByName("DeleteProvider")),
		connect.WithHandlerOptions(opts...),
	)
	return "/construct.v1.ModelProviderService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModelProviderServiceCreateProviderProcedure:
			modelProviderServiceCreateProviderHandler.ServeHTTP(w, r)
		case ModelProviderServiceGetProviderProcedure:
			modelProviderServiceGetProviderHandler.ServeHTTP(w, r)
		case ModelProviderServiceListProvidersProcedure:
			modelProviderServiceListProvidersHandler.ServeHTTP(w, r)
		case ModelProviderServiceUpdateProviderProcedure:
			modelProviderServiceUpdateProviderHandler.ServeHTTP(w, r)
		case ModelProviderServiceDeleteProviderProcedure:
			modelProviderServiceDeleteProviderHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModelProviderServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedModelProviderServiceHandler struct{}

func (UnimplementedModelProviderServiceHandler) CreateProvider(context.Context, *connect.Request[v1.CreateModelProviderRequest]) (*connect.Response[v1.CreateModelProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.CreateProvider is not implemented"))
}

func (UnimplementedModelProviderServiceHandler) GetProvider(context.Context, *connect.Request[v1.GetModelProviderRequest]) (*connect.Response[v1.GetModelProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.GetProvider is not implemented"))
}

func (UnimplementedModelProviderServiceHandler) ListProviders(context.Context, *connect.Request[v1.ListModelProvidersRequest]) (*connect.Response[v1.ListModelProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.ListProviders is not implemented"))
}

func (UnimplementedModelProviderServiceHandler) UpdateProvider(context.Context, *connect.Request[v1.UpdateModelProviderRequest]) (*connect.Response[v1.UpdateModelProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.UpdateProvider is not implemented"))
}

func (UnimplementedModelProviderServiceHandler) DeleteProvider(context.Context, *connect.Request[v1.DeleteModelProviderRequest]) (*connect.Response[v1.DeleteModelProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("construct.v1.ModelProviderService.DeleteProvider is not implemented"))
}
