// Code generated by ent. DO NOT EDIT.

package agent

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the agent type in the database.
	Label = "agent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldInstructions holds the string denoting the instructions field in the database.
	FieldInstructions = "instructions"
	// EdgeModel holds the string denoting the model edge name in mutations.
	EdgeModel = "model"
	// EdgeDelegates holds the string denoting the delegates edge name in mutations.
	EdgeDelegates = "delegates"
	// EdgeDelegators holds the string denoting the delegators edge name in mutations.
	EdgeDelegators = "delegators"
	// Table holds the table name of the agent in the database.
	Table = "agents"
	// ModelTable is the table that holds the model relation/edge.
	ModelTable = "agents"
	// ModelInverseTable is the table name for the Model entity.
	// It exists in this package in order to avoid circular dependency with the "model" package.
	ModelInverseTable = "models"
	// ModelColumn is the table column denoting the model relation/edge.
	ModelColumn = "model_agents"
	// DelegatesTable is the table that holds the delegates relation/edge. The primary key declared below.
	DelegatesTable = "agent_delegators"
	// DelegatorsTable is the table that holds the delegators relation/edge. The primary key declared below.
	DelegatorsTable = "agent_delegators"
)

// Columns holds all SQL columns for agent fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldInstructions,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "agents"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"model_agents",
}

var (
	// DelegatesPrimaryKey and DelegatesColumn2 are the table columns denoting the
	// primary key for the delegates relation (M2M).
	DelegatesPrimaryKey = []string{"agent_id", "delegate_id"}
	// DelegatorsPrimaryKey and DelegatorsColumn2 are the table columns denoting the
	// primary key for the delegators relation (M2M).
	DelegatorsPrimaryKey = []string{"agent_id", "delegate_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Agent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByInstructions orders the results by the instructions field.
func ByInstructions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstructions, opts...).ToFunc()
}

// ByModelField orders the results by model field.
func ByModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelStep(), sql.OrderByField(field, opts...))
	}
}

// ByDelegatesCount orders the results by delegates count.
func ByDelegatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDelegatesStep(), opts...)
	}
}

// ByDelegates orders the results by delegates terms.
func ByDelegates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDelegatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDelegatorsCount orders the results by delegators count.
func ByDelegatorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDelegatorsStep(), opts...)
	}
}

// ByDelegators orders the results by delegators terms.
func ByDelegators(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDelegatorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelTable, ModelColumn),
	)
}
func newDelegatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, DelegatesTable, DelegatesPrimaryKey...),
	)
}
func newDelegatorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, DelegatorsTable, DelegatorsPrimaryKey...),
	)
}
