// Code generated by ent. DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// ModelProvider is the predicate function for modelprovider builders.
type ModelProvider func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
