// Code generated by ent. DO NOT EDIT.

package task

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/furisto/construct/backend/memory/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdateTime, v))
}

// ProjectDirectory applies equality check predicate on the "project_directory" field. It's identical to ProjectDirectoryEQ.
func ProjectDirectory(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProjectDirectory, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldOutputTokens, v))
}

// CacheWriteTokens applies equality check predicate on the "cache_write_tokens" field. It's identical to CacheWriteTokensEQ.
func CacheWriteTokens(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCacheWriteTokens, v))
}

// CacheReadTokens applies equality check predicate on the "cache_read_tokens" field. It's identical to CacheReadTokensEQ.
func CacheReadTokens(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCacheReadTokens, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v float64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCost, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAgentID, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldUpdateTime, v))
}

// ProjectDirectoryEQ applies the EQ predicate on the "project_directory" field.
func ProjectDirectoryEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProjectDirectory, v))
}

// ProjectDirectoryNEQ applies the NEQ predicate on the "project_directory" field.
func ProjectDirectoryNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldProjectDirectory, v))
}

// ProjectDirectoryIn applies the In predicate on the "project_directory" field.
func ProjectDirectoryIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldProjectDirectory, vs...))
}

// ProjectDirectoryNotIn applies the NotIn predicate on the "project_directory" field.
func ProjectDirectoryNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldProjectDirectory, vs...))
}

// ProjectDirectoryGT applies the GT predicate on the "project_directory" field.
func ProjectDirectoryGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldProjectDirectory, v))
}

// ProjectDirectoryGTE applies the GTE predicate on the "project_directory" field.
func ProjectDirectoryGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldProjectDirectory, v))
}

// ProjectDirectoryLT applies the LT predicate on the "project_directory" field.
func ProjectDirectoryLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldProjectDirectory, v))
}

// ProjectDirectoryLTE applies the LTE predicate on the "project_directory" field.
func ProjectDirectoryLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldProjectDirectory, v))
}

// ProjectDirectoryContains applies the Contains predicate on the "project_directory" field.
func ProjectDirectoryContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldProjectDirectory, v))
}

// ProjectDirectoryHasPrefix applies the HasPrefix predicate on the "project_directory" field.
func ProjectDirectoryHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldProjectDirectory, v))
}

// ProjectDirectoryHasSuffix applies the HasSuffix predicate on the "project_directory" field.
func ProjectDirectoryHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldProjectDirectory, v))
}

// ProjectDirectoryEqualFold applies the EqualFold predicate on the "project_directory" field.
func ProjectDirectoryEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldProjectDirectory, v))
}

// ProjectDirectoryContainsFold applies the ContainsFold predicate on the "project_directory" field.
func ProjectDirectoryContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldProjectDirectory, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldInputTokens, v))
}

// InputTokensIsNil applies the IsNil predicate on the "input_tokens" field.
func InputTokensIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldInputTokens))
}

// InputTokensNotNil applies the NotNil predicate on the "input_tokens" field.
func InputTokensNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldInputTokens))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldOutputTokens, v))
}

// OutputTokensIsNil applies the IsNil predicate on the "output_tokens" field.
func OutputTokensIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldOutputTokens))
}

// OutputTokensNotNil applies the NotNil predicate on the "output_tokens" field.
func OutputTokensNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldOutputTokens))
}

// CacheWriteTokensEQ applies the EQ predicate on the "cache_write_tokens" field.
func CacheWriteTokensEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCacheWriteTokens, v))
}

// CacheWriteTokensNEQ applies the NEQ predicate on the "cache_write_tokens" field.
func CacheWriteTokensNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCacheWriteTokens, v))
}

// CacheWriteTokensIn applies the In predicate on the "cache_write_tokens" field.
func CacheWriteTokensIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCacheWriteTokens, vs...))
}

// CacheWriteTokensNotIn applies the NotIn predicate on the "cache_write_tokens" field.
func CacheWriteTokensNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCacheWriteTokens, vs...))
}

// CacheWriteTokensGT applies the GT predicate on the "cache_write_tokens" field.
func CacheWriteTokensGT(v int64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCacheWriteTokens, v))
}

// CacheWriteTokensGTE applies the GTE predicate on the "cache_write_tokens" field.
func CacheWriteTokensGTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCacheWriteTokens, v))
}

// CacheWriteTokensLT applies the LT predicate on the "cache_write_tokens" field.
func CacheWriteTokensLT(v int64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCacheWriteTokens, v))
}

// CacheWriteTokensLTE applies the LTE predicate on the "cache_write_tokens" field.
func CacheWriteTokensLTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCacheWriteTokens, v))
}

// CacheWriteTokensIsNil applies the IsNil predicate on the "cache_write_tokens" field.
func CacheWriteTokensIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldCacheWriteTokens))
}

// CacheWriteTokensNotNil applies the NotNil predicate on the "cache_write_tokens" field.
func CacheWriteTokensNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldCacheWriteTokens))
}

// CacheReadTokensEQ applies the EQ predicate on the "cache_read_tokens" field.
func CacheReadTokensEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensNEQ applies the NEQ predicate on the "cache_read_tokens" field.
func CacheReadTokensNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensIn applies the In predicate on the "cache_read_tokens" field.
func CacheReadTokensIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensNotIn applies the NotIn predicate on the "cache_read_tokens" field.
func CacheReadTokensNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensGT applies the GT predicate on the "cache_read_tokens" field.
func CacheReadTokensGT(v int64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCacheReadTokens, v))
}

// CacheReadTokensGTE applies the GTE predicate on the "cache_read_tokens" field.
func CacheReadTokensGTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCacheReadTokens, v))
}

// CacheReadTokensLT applies the LT predicate on the "cache_read_tokens" field.
func CacheReadTokensLT(v int64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCacheReadTokens, v))
}

// CacheReadTokensLTE applies the LTE predicate on the "cache_read_tokens" field.
func CacheReadTokensLTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCacheReadTokens, v))
}

// CacheReadTokensIsNil applies the IsNil predicate on the "cache_read_tokens" field.
func CacheReadTokensIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldCacheReadTokens))
}

// CacheReadTokensNotNil applies the NotNil predicate on the "cache_read_tokens" field.
func CacheReadTokensNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldCacheReadTokens))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v float64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v float64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...float64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...float64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v float64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v float64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v float64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v float64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCost, v))
}

// CostIsNil applies the IsNil predicate on the "cost" field.
func CostIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldCost))
}

// CostNotNil applies the NotNil predicate on the "cost" field.
func CostNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldCost))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...uuid.UUID) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDIsNil applies the IsNil predicate on the "agent_id" field.
func AgentIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldAgentID))
}

// AgentIDNotNil applies the NotNil predicate on the "agent_id" field.
func AgentIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldAgentID))
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.Message) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgent applies the HasEdge predicate on the "agent" edge.
func HasAgent() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AgentTable, AgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentWith applies the HasEdge predicate on the "agent" edge with a given conditions (other predicates).
func HasAgentWith(preds ...predicate.Agent) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Task) predicate.Task {
	return predicate.Task(sql.NotPredicates(p))
}
